### ISSUE TITLE
Scheduler not working for RDS instances 

### ISSUE THREAD

**Issue by thedusansky1** [neillturner/terraform-aws-lambda-scheduler#13]
**SUMMARY**

Hello team, 

I've applied the module using Terraform v0.12.24 and set the values for the EC2 and RDS tags as per instructions. 
Scheduler is working fine for the EC2 instances, starting/stopping them at defined intervals. However, it is never triggered for the RDS instances. Could the issue lies in format of the value that we are passing to the RDS tag? 

As per instructions the value of the RDS tag should be a string with double quotes at the beggining and the end. 

Example of the value: _"mon_start=7 mon_stop=20 tue_start=7 tue_stop=20 wed_start=7 wed_stop=20 thu_start=7 thu_stop=20 fri_start=7 fri_stop=20"_

RDS tags are not supporting symbols like ", so we can only pass a value without quotes, in this case: _mon_start=7 mon_stop=20 tue_start=7 tue_stop=20 wed_start=7 wed_stop=20 thu_start=7 thu_stop=20 fri_start=7 fri_stop=20_

This unfotunatelly never triggers scheduler and RDS instances are never stopped/started. 
Could you please share if you are facing the same issue? 
If the module is working fine with your RDS instances, please share the example of the value that you are passing to RDS tag. 

Thank you in advance! 

**ISSUE TYPE**    

- Bug Report

**EXPECTED RESULTS**

Ec2 and RDS instances to start/stop by scheduler at defined intervals 
**ACTUAL RESULTS**

Scheduler is working only for the EC2 instances

**Comment by neillturner** [comment]
the example works: 
set the schedule tag on the RDS to
"mon_start=7 mon_stop=20 tue_start=7 tue_stop=20 wed_start=7/22 wed_stop=20 thu_start=7 thu_stop=2/20 fri_start=7 fri_stop=20"
if it is not work look in the cloudwatch logs and you should see log output.
