### ISSUE TITLE
Error calling scheduler

### ISSUE THREAD

**Issue by dscowan** [neillturner/terraform-aws-lambda-scheduler#3]
[INFO]	2018-11-26T15:27:09.491Z	xxxx 	Evaluating EC2 instance "xxxxxxxxxxxxxxxxxxxx"
'NoneType' object is not iterable: TypeError
Traceback (most recent call last):
  File "/var/task/aws-scheduler.py", line 261, in handler
    check()
  File "/var/task/aws-scheduler.py", line 94, in check
    for tag in instance.tags:
TypeError: 'NoneType' object is not iterable

**Comment by neillturner** [comment]
I suspect you have the environment variable 
RDS_SCHEDULE
set to nothing instead of True or False. 
in the log you should see a message 
logger.info("rds_schedule is %s." % rds_schedule)
the parameter setup is not bullet-proof. -)

**Comment by neillturner** [comment]
closing
