### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by rstuartVT** [neillturner/terraform-aws-lambda-scheduler#4]
How is timezone calculated? I'm in CST timezone and deployed in us-east-1, I have the stop set to 18 and time set to local. but the instance was stopped at 12:05 PM CST/18:05 GMT

**Comment by neillturner** [comment]
I'm restricted to timezone options of python - 'local' or 'gmt'. 
local is the time at the aws datacentre region no where you happen to be. 
Doesn't work well with daylight saving changes. 
Open to any improvements.

**Comment by rstuartVT** [comment]
does 'local' work during non-DLS times? it should only be at most 1 hour off if it was using the local setting correctly, and just not taking into account DLS.

**Comment by googley** [comment]
Could you use `pytz`?

**Comment by neillturner** [comment]
thanks for the suggestion. when i get a moment i will try it.

**Comment by neillturner** [comment]
enhanced in Version 0.4.0 
Using Olson Time zones should solved Daylight Saving Issues.

**Comment by rstuartVT** [comment]
so for us-east-1 would be America/New_York?
time = "America/New_York"
