### ISSUE TITLE
RDS Scheduling not working

### ISSUE THREAD

**Issue by Pianist038801** [neillturner/terraform-aws-lambda-scheduler#6]
Greetings!

Today, I found this nice module and integrated it into my project.

It works perfectly fine for EC2 instances, but not for RDS.

I see one of the commits named "RDS scheduling is broken". 

Is it still broken or is that commit actually fixing the issue?

I'll be grateful if you reply shortly as this is urgent for me. 

Thanks in advance.

Best Regards.

**Comment by neillturner** [comment]
unfortunately i didn't get a reply for that one. i believe it works. let me test today.

**Comment by Pianist038801** [comment]
Thanks for your kind reply. Yes, it works. I tested it out.

Best Regards.

**Comment by neillturner** [comment]
works for rds instances, will work for clusters when pull request Supporting Multiple Start/Stop Times per Day and RDS Clusters #7 is merged.
